### ISSUE TITLE
App jsut crashes

### ISSUE THREAD

**Issue by Gustorvo** [trev3d/QuestDisplayAccessDemo#1]
I'd love to contrubute but cannot launch the app, it just crushes when I allow casting on app launch. If denyed casting, app wil start but not being able to retrieve the texture data of course.

**Comment by trev3d** [comment]
Can you provide a stack trace?

**Comment by Gustorvo** [comment]
sure! 
[odh_logs_2024-08-23 13.34.27.126.txt](https://github.com/user-attachments/files/16729394/odh_logs_2024-08-23.13.34.27.126.txt)

**Comment by Gustorvo** [comment]
The issue is fixed by updating the headset to the latest v68 firmware !!!
