### ISSUE TITLE
Microphoe Permission 

### ISSUE THREAD

**Issue by suibiweng** [trev3d/QuestDisplayAccessDemo#14]
Hi,
I want to thank you first this is helping my project.
Nevertheless, I found an issue with the microphone permission.
My guessing is It conflicts with microphone permission access.
I need to use speech-to-text in the project. Is there any way that I can fix it?

**Comment by trev3d** [comment]
Within AndroidManifest.xml there should be a line that *removes* the microphone permission. You need to delete this line so that your app can access the microphone on Horizon OS (Android)

**Comment by suibiweng** [comment]
Thanks! I will try

**Comment by Jocarfl** [comment]
Hi, I have a problem with the microphone and I don't know if it goes the same way as this issue. 

I'm in a project which is basically like a skype where you can make p2p calls with other users. And when I share screen with the other user using ScreenCapture the audio of the call is cut (I don't listen to the other participant and he doesn't listen to me). Any idea what can happen? How did you manage to solve your microphone problem @suibiweng?

**Comment by DomoMKT** [comment]
you're looking for a reliable solution to convert text to high-quality speech with low latency - i've got you covered, and [www.nemesyslabs.com](https://www.nemesyslabs.com) is where you'll find the perfect fit!

**Comment by suibiweng** [comment]
Hi, I haven't found a good way to do that.
My current solution is to turn off the permission every time manually from the Qculus setting, which allows the application to re-confirm the permission, and that works for now.
