### ISSUE TITLE
Usable with OpenXR and OpenXR: Meta Packages

### ISSUE THREAD

**Issue by davidfufu** [trev3d/QuestDisplayAccessDemo#16]
Hi there, I notice that DepthKit uses Utils from Unity.XR.Oculus as well as EnvironmentDepthManager from Meta SDK. I'm trying to stick with the OpenXR and the OpenXR: Meta Feature Group package. Is there a way to bootstrap this to work without using the Meta SDK?

**Comment by trev3d** [comment]
I rely on Meta's depth API to estimate the poses of arbitrarily sized QR codes. It is not strictly necessary if all you need is the camera frames. However, I don't know how to interface with the depth API through OpenXR extensions if you need it

**Comment by arkantose** [comment]
The actual screen projection doesn't rely on the Oculus sdk. That's just
the player setup. You can assign it to any texture and replace the player
rig with whatever you want. The media projection is based off of the
android sdk which is completely separate from any vr mechanics.

**Comment by davidfufu** [comment]
That makes sense, @trev3d. And your usage of the depth API is for the continuous tracking and placement of the tracking border around the QR code right?
