### ISSUE TITLE
Black screen on Quest3

### ISSUE THREAD

**Issue by markbland82** [trev3d/QuestDisplayAccessDemo#4]
Not sure if I am missing any specific setup elements but everything seems to load just no passthrough (black screen/background). Is this sideloaded or pc linked? 

Thanks!

**Comment by trev3d** [comment]
It only works running on the headset directly. It won’t work over link

**Comment by markbland82** [comment]
Thank you!

**Comment by trev3d** [comment]
Are you still having an issue with the project?

**Comment by markbland82** [comment]
Looks to be working now :) Thanks very much!
