### ISSUE TITLE
Get ScreenCapture working for OpenXR-Build on Quest 3

### ISSUE THREAD

**Issue by mount-whitey** [trev3d/QuestDisplayAccessDemo#5]
Hey trev3d,

my project is set up with the OpenXR-Background and I can't change so easy back to Oculus (like your example)... so I've tried to include your work in the OpenXR space, but get always the follown error... 

"java.lang.NoSuchMethodError: no non-static method with name='startScreenCaptureWithPermission' signature='(Ljava/lang/String;II)V' in class Lcom.unity3d.player.UnityPlayerActivity;"

 I've also seen that you included the "RecordNotificationService.java" library in the AndroidManifest for the Oculus-Build in the XR-Management. 

I am an absolute newbie in Java plugins so have you any help for me, how I could get ScreenCapture work in the OpenXR space?

Have you got the capture functionality already running for OpenXR backend OR are you planning to get it work for this backend?

Thanks for your help :)

All best!

**Comment by trev3d** [comment]
The project relies on a modified UnityPlayerActivity which includes the code for screen capture. That is in `UnityPlayerActivityWithMediaProjector.java`. **You must specify this class as the launch activity in your manifest.** See the `<activity>` bit of the project's manifest :)

**Comment by mount-whitey** [comment]
Thank you trev3d! 

I had completely overlooked the other part after it was hidden so far back in the line!

Works great now.

P.S. for all those who want to integrate the ScreenCapture into their application... you should add the following colored lines to your setup.

<img width="740" alt="Manifest_MODIFICATION" src="https://github.com/user-attachments/assets/030f4924-73b8-4de0-9c29-fb8ae1df3ba3">

All the best :)
