### ISSUE TITLE
Sample apk

### ISSUE THREAD

**Issue by liveasnotes** [trev3d/QuestDisplayAccessDemo#7]
Thank you for the great demo!
I ​​would be grateful if you could also include the latest apk file in the repository.

I first built ScreenCaptureTexture/SampleScene.unity and ran it on Quest 3 (v68), but the texture remains purple.
I would like to have a build that is confirmed to work in your environment so that I can determine whether the project is broken or there is a problem with my device.

**Comment by JaredBBraun** [comment]
From my experience, it looks like the 'SampleScene' isn't supported anymore and because of this, I used the `AprilTagDemo` scene and it works fine

**Comment by JaredBBraun** [comment]
I think we can use better build documentation and project config set up from @trev3d

**Comment by trev3d** [comment]
I'll check the project. I might've forgotten to update SampleScene as I meant to make the April tag demo the 'main' example scene

**Comment by trev3d** [comment]
Removed both old demo scenes in favor of one main scene that demonstrates both screen capture and apriltag tracking
